podengo-project/idmsvc-backend

scripts/mk/printvars.mk
This new rule will help to know the configuration environment variables that are exported for the commands executed by the makefile.
=> feat: add printenvcfg rule

.rhcicd/build_deploy.sh, scripts/mk/ephemeral.mk, test/scripts/ephe-domains-token.sh
`build_deploy.sh` runs container-push after container-build (fix for parallel builds with `MAKEFLAGS` env var)
`make ephemeral-deploy` creates secrets directory, `bonfire.yaml` from example, and fails if `secrets/private.mk` is missing.
`make ephemeral-build-deploy` fails if the `build_deploy.sh` script fails.
`ephe-domains-token.sh` uses correct XRHID identity type. Tokens are requested as user, not system.
=> fix: Misc ephemeral deployment fixes

internal/config/config.go, internal/test/config_helper.go, scripts/mk/ephemeral.mk, scripts/mk/variables.mk
Fix 065eb0c4 was wrong. `v.AutomaticEnv` is required.
It turned out that the root cause of the issue was Makefile's env var `APP`. It conflicts with Viper's map structure `app`. Due to `APP=idmsvc`, Viper resets the entire `Config.Application` struct to empty defaults, then applies additioanl env var settings.
Fix:
- Rename Makefile variable and export from `APP` to `APP_NAME`
- Enable automatic env again
=> HMS-2606 fix: Fix config loading from env (part 2)

scripts/mk/compose.mk
The `db migrate-up` step of `make compose-up` no longer fails when `configs/config.yaml` does not exist or has different settings.
Also indent some lines to indicate that it's a continuation line.
=> fix: compose-up without configs/config.yaml

internal/handler/impl/keys_handler.go
The GET `signing_keys` route now returns an empty result set instead of an error. The change is necessary to unbreak integration testing of`ipa-hcc`.
=> HMS-2595 fix: GET signing_keys dummy

internal/api/public/spec.gen.go
Update the generated spec.gen.go file after the new API has been attached.
=> HMS-2590 fix: use 'resources' tag for PATCH /domains/:domain_id

internal/infrastructure/token/jwk.go, internal/infrastructure/token/jwk_test.go
Implement functions to create a new JWK with expected properties and load a serialized JWK.
`GenericePrivateJWK()` creates a private JWK with EC / P256, kid, and expiration time stamp.
`GetPublicJWK()` is a helper to create a public JWK from a private JWK.
`ParseJWK()` deserializes a JWK string that has been previously serialized with `json.Marshal`. The function validates various properties including expiration.
=> HMS-2693 feat: Implement JWK creation and load

internal/infrastructure/token/hostconf_token.go, internal/infrastructure/token/hostconf_token_test.go, internal/infrastructure/token/jwk.go, internal/infrastructure/token/variables.go
Add helpers to build a host configuration token and to sign a token with multiple keys.
`BuildHostconfToken()` builds a new token and returns a token instance.
`SignToken()` signs a token with multiple keys and returns a JSON string.
=> HMS-2694 feat: Host conf token signing

internal/handler/impl/application.go, internal/handler/impl/host_handler.go, internal/handler/impl/keys_handler.go, internal/infrastructure/token/jwk.go, internal/interface/interactor/host_interactor.go, internal/interface/presenter/host_presenter.go, internal/interface/repository/host_repository.go, internal/test/mock/interface/presenter/host_presenter.go, internal/test/mock/interface/repository/host_repository.go, internal/test/variables.go, internal/usecase/interactor/host_interactor.go, internal/usecase/interactor/host_interactor_test.go, internal/usecase/presenter/host_presenter.go, internal/usecase/presenter/host_presenter_test.go, internal/usecase/repository/host_repository.go, test/scripts/ephe-signing-keys.sh, test/scripts/local-hostconf.sh, test/scripts/local-signing-keys.sh
Implement minimal host conf token and signing JWK.
A private ECDSA key is genenerated from a hard-coded seed and the JWK is
stored in memory. In the future, the ECDSA key will be generated from a
random source and the JWK stored in the database.
The `GET /signing_keys` endpoint returns the public JWK.
The `POST /host-conf` endpoint now returns a signed token.
Signed-off-by: Christian Heimes <cheimes@redhat.com>
=> HMS-2694 feat: Host conf token MVP

internal/usecase/repository/host_repository.go
A domain with `auto_enrollment_enabled = FALSE` should not be
returned in a host-conf response.  Iterate the returned records (no
longer limited to 2) and exclude disabled domains.
Also improve the HTTP response status for some expected ways
host-conf can fail.
- No matching domains (500 -> 404)
- Multiple matching domains (500 -> 409)
Also remove a seemingly obsolete comment.
=> HMS-2694 fix: exclude disabled domains from host-conf

internal/handler/impl/domain_handler.go
Currently when deleting an unknown record the service responds with 500 Internal Server Error.  Discriminate this case and respond with 404 Not Found instead.
=> fix: respond 404 when asked to delete unknown domain

internal/infrastructure/middleware/validate_api.go, internal/infrastructure/middleware/validate_api_test.go
The validation regexes for the description and title fields are too
restrictive.  Reasonable values are rejected.
Instead, use callback validators to check that the string values
(which are byte sequences) are valid UTF-8, and they do not contain
control characters (except the description field allows Carriage
Return, Line Feed, and Horizontal Tab).
ALSO
Currently input validation failure does NOT cause processing to
stop.  If somehow the backend operation succeed, that can result in
a 400 Bad Request response, but the target backend operation
completed and database modifications potentially performed.
Also, the normal response data gets appended to the error message.
Update the validation middleware to stop processing when an input
validation error occurs, after setting the response …
=> HMS-2714 fix description and title validation

.github/workflows/main.yml, .gitlab-ci.yml, go.sum, scripts/mk/go-rules.mk
`go get -d` and `go mod tidy` generate slightly different `go.sum` files. Dependabot uses `go mod tidy`, resulting in CI errors. Replace `go get -d` with `go mod download` and use the `go.sum` output of `go mod tidy`.
=> infra: Use go.sum from go mod tidy

scripts/mk/container.mk, scripts/mk/private.example.mk
The images generated by the pipeline are deleted after 1d. This change fixes
the situation by setting the quay.expire-after label into the container images
by default to the value of 'never' which avoids the image being deleted. To let
the developer build its own images during the development lifecycle, that
value can be customized from the scripts/mk/private.example.mk template.
=> fix: Changing expiration time to never

internal/infrastructure/middleware/validate_api.go
We should not return a plaintext error response as the error won't be displayed in this case. By returning a new HTTP error the default error handler of the echo server will take care of it creating the error response in the correct format. As this is a REST API, the error will be returned in json format.
Pair-Programmed-With: Alejandro Visiedo
Steps to reproduce to check the errors:
```
$ make compose-down clean build compose-up run
...
$ ./test/scripts/local-domains-token.sh             
HTTP/1.1 200 OK
Content-Type: application/json; charset=UTF-8
X-Content-Type-Options: nosniff
X-Frame-Options: SAMEORIGIN
X-Rh-Insights-Request-Id: test_52c262bd78e14daa835e
X-Xss-Protection: 1; mode=block
Date: Fri, 20 Oct 2023 11:15:10 GMT
Content-Length: 175 …
```
=> HMS-2837 fix: middleware validation error response

deployments/backend-compose.yaml, deployments/docker-compose.yaml
The compose currently attempts to connect as the container user "root".  This role does not exist in the postgresql server.  The liveness test does succeed, but it fills the "log" (stdout) with annoying messages:
... FATAL:  role "root" does not exist
`pg_isready` recognises the standard *libpq* environment variables: https://www.postgresql.org/docs/16/libpq-envars.html.  Set the `PGDATABASE`, `PGUSER` and `PGPASSWORD` environment variables in the database container environment to ensure that the connect test uses a valid account.  As a result, the log output no longer contains the the above message every few seconds.
=> compose: use correct account for healthcheck

internal/handler/impl/domain_handler.go, internal/handler/impl/domain_handler_private.go, internal/usecase/repository/domain_repository.go
A series of commits addressing HMS-1832.  Recommended to review each commit in sequence, rather than the whole PR diff all at once.
**Why no tests?**  The behavioural changes are mainly at the handler level, and there is no easy way to test that at this time.  Following discussions with @avisiedo , we propose to implement a "smoke test" framework in a (near) future sprint.  It can make it easy to test server behaviour via the service HTTP API, playing out the various scenarios and asserting that response statuses and payloads match expectations.  When this is implemented, it will be straightforward to test the behaviour in this PR - and I shall implement the tests!
```
commit 0d90e0b0e32c8a1c08d37d84fafde46d16253b26
Author: Fraser Tweedale <ftweedal@redhat.com>
Date:   Tue Oct 31 16:36:53 …
```
=> HMS-1832: update domain fixes

internal/infrastructure/middleware/authenticator_test.go, internal/usecase/repository/domain_repository_test.go
It was observed during a code review that some unit tests did not raised error on expectations changes. This change fix that situation by using EqualError to check the expectations which checks that an error happens and the string representation match with the string provided at the unit test expectation.
=> HMS-3070 fix: use EqualError on unit tests

build/package/Dockerfile, scripts/mk/container.mk
Our container images now have a label `idmsvc-backend` with value `builder` (for temporary Go builder container) or `backend` (for the actual backend container). The builder container is automatically pruned at the end of `make container-build`.
A new make target `container-clean` prunes and removes all local containers with a `idmsvc-backend` label.
=> infra: Add make container-clean

internal/usecase/presenter/host_presenter.go
Add `--mkhomedir` and `--subid` options to `ipa-client-install` for demo. This configures mkhomedir oddjob and SSSD's subordinate ID provider.
=> feat: IPA client install with mkhomedir and subid

cmd/service/main.go, internal/infrastructure/logger/init.go, scripts/mk/go-rules.mk
The service now shows version, git commit revision / time stamp, and dirty flag on startup. The information is provided by `runtime/debug` package since Golang 1.18.
`go build` bakes the VCS information into the binary if-and-only-if the main module is references by path to a directory.
=> HMS-3190 feat: Show VCS information on app startup

internal/handler/impl/domain_handler.go
Update the returned code by the RegisterDomain handler for a success domain registration, so it return a 201 Created, instead of a 200 Ok status code.
=> HMS-3138 fix: return 201 when a domain is registered

scripts/mk/ephemeral.mk, scripts/mk/private.example.mk
Update to use the new ephemeral cluster and to quickly change to even another cluster if it were necessary just providing the CLUSTER variable from the command line to the make invokation or updating our makefile customizations.
=> HMS-3414 build: update ephemeral cluster

deployments/clowder.yaml
This change introduce the dependency of the idmsvc-backend on the "rbac" service, so it is made available when iqe is launched and when developing the integration with rbac service.
=> HMS-3430 fix: add rbac dependency

internal/infrastructure/middleware/enforce_identity.go, internal/infrastructure/middleware/enforce_identity_test.go, internal/infrastructure/router/public.go
This change provide a deterministic order when the enforce identity middleware is applied, when more than one predicate is provided.
=> HMS-2182 refactor: enforce identity order

internal/config/event.go, internal/infrastructure/event/topics_test.go
Clowder configuration may have AppConfig.Kafka set to `nil`. The function `NewTopicTranslationWithClowder` was not checking the value for nil and crashed when it attempted to iterate over cfg.Kafka.Topics.
=> HMS-3474 fix: Check for clowder AppConfig.Kafka for nil

.dockerignore, build/package/Dockerfile
Do not exclude `.git` directory from Docker COPY, so `go build` is able to figure out and include VCS information in binaries that are built inside a container.
=> HMS-3190 fix: Include VCS info in container binaries

build/package/Dockerfile
The `ubi9-minimal` image contains everything we need to run our app and enough infrastructure for interactive debugging. Also install security updates with `microdnf`.
=> infra: Use minimal UBI image with updates

.pre-commit-config.yaml, scripts/mk/go-rules.mk, scripts/mk/variables.mk, tools/go.mod, tools/go.sum
`tools/go.mod` was using Go version 1.21, but our build container is limited to 1.20. Address build confusion by downgrading to a working go-jsonschema version and pinning `go mod tidy` to 1.20.
Introduce `pr-check` to run most important and fast linting, formatting, and testing steps.
=> HMS-3559 infra: Fix Go version confusion / pr-check

.gitignore, internal/config/config.go, internal/handler/impl/application.go, internal/handler/impl/application_test.go, internal/handler/impl/domain_handler.go, internal/handler/impl/host_handler.go, internal/handler/impl/keys_handler.go, internal/infrastructure/secrets/app_secrets.go, internal/infrastructure/secrets/app_secrets_test.go, internal/infrastructure/secrets/hkdf.go, internal/infrastructure/secrets/hkdf_test.go, internal/infrastructure/token/domain_token/domain_token.go, internal/infrastructure/token/domain_token/domain_token_test.go, internal/infrastructure/token/hostconf_jwk/encrypt.go, internal/infrastructure/token/hostconf_jwk/encrypt_test.go, internal/infrastructure/token/hostconf_jwk/jwk.go, internal/infrastructure/token/hostconf_jwk/jwk_test.go, internal/infrastructure/token/hostconf_jwk/variables.go, internal/infrastructure/token/hostconf_token/hostconf_token.go, internal/infrastructure/token/hostconf_token/hostconf_token_test.go, internal/infrastructure/token/hostconf_token/variables.go, internal/test/config_helper.go, internal/usecase/interactor/domain_interactor.go, internal/usecase/interactor/domain_interactor_test.go, internal/usecase/repository/domain_repository.go, internal/usecase/repository/domain_repository_test.go, internal/usecase/repository/host_repository.go
Split the token package into three separate packages and move the HKDF code into a new `secrets` package.
- `hostconf_token` deals with host configuration token
- `hostconf_jwk` handles private and public JWKs for host configuration token
- `domain_token` deals with domain registration tokens
- new `secrets` expands and extracts secrets from the main app secret
- secrets are now part of `config` structure in an untagged struct member (therefore not handled by viper)
=> HMS-2694 refactor: Split token package

internal/infrastructure/datastore/migration.go
The `db-tool` now prints migration information before and after migration. `No new migrations` is now logged with level `INFO`.
Examples:
```
level=INFO msg="No database version"
level=INFO msg="New database migration status" version=20230125102205 dirty=false
```
```
$ bin/db-tool migrate up 0
level=INFO msg="Current database migration status" version=20230125102205 dirty=false
level=INFO msg="No new migrations"
```
=> feat: Show db version during migration

.vscode/launch.json, cmd/db-tool/cmd/jwk-refresh.go, cmd/db-tool/cmd/jwk.go, cmd/db-tool/cmd/root.go, deployments/clowder.yaml, scripts/mk/db.mk
The `db-tool` command now has a subcommand to refresh JWKs. The subcommand doesn't do anything besides printing a string. The actual refresh code will be implemented later.
- add dummy implementation of `db-tool jwk refresh`
- update cloweder template to run refresh in init container and as periodic job. The cron job runs every hour, which makes testing and debug a bit easier. Later one we could reduce the schedule to daily.
- run `db-tool jwk refresh` during `make db-migrate-up`
=> HMS-2694 feat: Add boilerplate for JWK key refresh

.golangci.yaml, .vscode/settings.json, configs/config.ci.yaml, configs/config.example.yaml, deployments/clowder.yaml, internal/config/config.go, internal/config/config_test.go, internal/infrastructure/middleware/rbac.go, internal/infrastructure/middleware/rbac_test.go, internal/infrastructure/router/public.go, scripts/mk/variables.mk
This change add the configuration and skeleton for the RBAC middleware and unit tests.
The default value at config will be enabled in the code, but will be disabled until the implementation is full finished at HMS-3528
Checked by:
- `APP_ENABLE_RBAC=false make test-smoke` # run successfully
- `APP_ENABLE_RBAC=true make test-smoke`  # Fail with 403
- `make test` # Run successfully
=> feat(HMS-3521): Add configuration to enable/disable RBAC middleware

configs/config.example.yaml, internal/config/config.go, internal/config/config_test.go, internal/infrastructure/secrets/app_secrets.go, internal/infrastructure/secrets/app_secrets_test.go, internal/infrastructure/secrets/hkdf.go, internal/test/config_helper.go
Add configuration settings for hostconf JWK expiration and refresh threshold. The minimum values are set to 1 minute for easier testing.
Remove support for `random` app secret. Random keys are incompatible with persistent JWKs. Local example configuration now uses the same secret as Makefile. Ephemeral and stage get their secret from Vault.
Note: ParseDuration does not support days.
=> HMS-2694 feat: Config changes for JWK in DB

internal/infrastructure/token/hostconf_jwk/model/hostconf_jwk_model.go, internal/infrastructure/token/hostconf_jwk/model/hostconf_jwk_model_test.go, internal/infrastructure/token/hostconf_jwk/variables.go, scripts/db/migrations/20240130080519_hostconf_jwks.down.sql, scripts/db/migrations/20240130080519_hostconf_jwks.up.sql
Add helper methods to HostconfJwk GORM model that deal with
public/private key state, deserialization of public JWK and decryption
of private JWK. The factory function `NewHostconfJwk` creates a new
HostconfJwk item with public and encrypted private JWK.
=> HMS-2694 feat: Hostconf JWK model and table

internal/domain/model/domain.go, internal/domain/model/domain_test.go, internal/infrastructure/token/hostconf_jwk/model/hostconf_jwk_model.go, internal/infrastructure/token/hostconf_jwk/model/hostconf_jwk_model_test.go
There is no need to populate CreatedAt and UpdatedAt fields with a custom hook. Gorm maintains the fields automatically for us.
See: https://gorm.io/docs/models.html#gorm-Model
=> refactor: Remove unnecessary BeforeCreate hook

cmd/db-tool/cmd/jwk-list.go, cmd/db-tool/cmd/jwk-purge.go, cmd/db-tool/cmd/jwk-revoke.go, cmd/db-tool/cmd/jwk.go, configs/config.example.yaml, internal/handler/impl/keys_handler.go, internal/infrastructure/datastore/hostconf_jwk_db.go, internal/infrastructure/token/hostconf_jwk/jwk.go, internal/infrastructure/token/hostconf_jwk/model/hostconf_jwk_model.go, internal/interface/presenter/hostconf_jwk_presenter.go, internal/interface/repository/hostconf_jwk_repository.go, internal/test/mock/interface/presenter/hostconf_jwk_presenter.go, internal/test/mock/interface/repository/hostconf_jwk_repository.go, internal/usecase/presenter/hostconf_jwk_presenter.go, internal/usecase/presenter/hostconf_jwk_presenter_test.go, internal/usecase/repository/hostconf_jwk_repository.go, internal/usecase/repository/hostconf_jwk_repository_test.go
The Hostconf JWKs are now stored and retrieved from database. Keys are
created and refreshed on startup, either by an init container or by
`make db-migrate-up` call.
The `db-tool` has commands to list, purge, refresh, and revoke keys.
```
$ bin/db-tool jwk
Hostconf JWK management
Available Commands:
list        List JWKs
purge       Purge expired JWK
refresh     Refresh or create JWKs
revoke      Revoke a JWK
```
=> HMS-2694 feat: Store Hostconf JWKs in DB

internal/infrastructure/logger/init.go
This will always log an info message on the console on startup and tell us how logging will be configured.
Example:
`time=2024-03-06T11:31:24.289+01:00 level=INFO msg=idmsvc-backend Logging.Console=true Logging.Type=null Logging.Level=warn`
=> HMS-3603 feat(logging): Add a log message about the logging setup

deployments/clowder.yaml
Fixes:
```
* spec.deployments[0].podSpec.env[2].value: Invalid value: "boolean": spec.deployments[0].podSpec.env[2].value in body must be of type string: "boolean"
```
=> Fix: logging location needs simple template for boolean

internal/infrastructure/middleware/enforce_identity.go, internal/infrastructure/middleware/enforce_identity_test.go, internal/infrastructure/router/public.go, internal/infrastructure/router/public_test.go
This change allow to define routes for mixed enforcement for the routes that could be reached out by users or systems.
=> fix(HMS-3805): add mixed enforcement

internal/config/config.go, internal/config/config_test.go
This workaround would fix the cloudwatch situation, so
the type field is filled with `"coudwatch"` string when
the cloudwatch values are merged on the service configuration.
When https://github.com/RedHatInsights/clowder/pull/627 PR
is merged, we can revert the first commit of this PR.
=> fix(HMS-3731): workaround for cloudwatch type field

tools/go.mod, tools/go.sum
This change add a replace directive to fix the dependency
on `go.tmz.dev/musttag`.
=> fix(HMS-4004): tools/go.mod dependency on go.tmz.dev/musttag

.dockerignore
Add a policy to ignore by default from .dockerignore file. As .git is not copied, the printing out the last commit is made from the container-build rule. For internal CI/CD we can track the repository related state by the image tag which is the short hash of the repository.
Credits on: insights-rbac contributors
=> fix(HMS-3914): harden dockerfile

internal/test/smoke/register_test.go, internal/usecase/interactor/domain_interactor.go, internal/usecase/interactor/domain_interactor_test.go
When the register operation happens, it is set
auto-enrollment to false by default. This is for
the `POST /domains` operation.
Later the user decide if it is enable or disabled
with a `PATCH /domains/:domain_id` operation, which
match with clicking on the **Finish** button on the
registration domain wizard.
It can be checked by:
```shell
make compose-clean clean build commpose-up run
./test/scripts/local-domain-token.sh
TOKEN="..."  # the value returned for it
./test/scripts/local-domain-register "$TOKEN"
make db-cli
select * from domains;
```
=> fix(HMS-4061): fix auto enrollment

internal/test/smoke/rbac_permission_test.go
Add smoke tests to check permissions for read-only operations.
This use all the previous infrastructure, so we only have to
describe the status code for the operations unauthorized.
Depends on: https://github.com/podengo-project/idmsvc-backend/pull/169
=> test(HMS-3524): read only permission

internal/test/smoke/rbac_permission_test.go, internal/usecase/client/rbac/wrapper.go
This change add integration tests to verify the
response for the operations is unauthorized when
none of the permissions are returned.
Depends on: https://github.com/podengo-project/idmsvc-backend/pull/169
=> test(HMS-3526): check rbac when no permissions

internal/handler/impl/domain_handler.go, internal/handler/impl/host_handler.go, internal/infrastructure/middleware/rbac.go, internal/infrastructure/middleware/rbac_test.go, internal/infrastructure/router/public.go, internal/infrastructure/router/rbac.yaml, internal/infrastructure/service/impl/mock/rbac/impl/rbac.go, internal/test/builder/api/builder_domain_rhel_idm_server.go, internal/test/builder/api/builder_host_conf.go, internal/test/builder/model/builder_hostconf_jwk.go, internal/test/smoke/rbac_permission_test.go, internal/test/smoke/suite_base_test.go, internal/test/smoke/system_endpoints_test.go, internal/usecase/repository/host_repository.go, internal/usecase/repository/hostconf_jwk_repository.go
System calls are failing; this change fix the situation calling to rbac endpoints when it is required.
The tests for the System endpoints has been extracted in its own test suite and additional endpoints for the smoke tests has been added there. A new builder is added for HostConfJwk instances, it prints more logs for the HostConf endpoint handler when an error happens.
Additionally
- a confusing error message when rbac mock close connection is removed.
- it fix rbac mapping created for the unit tests of the rbac middleware.
- add missed `/api/idmsvc/v1/signing_keys` at the system enforcement routes.
- include suggestions from @pvoborni .
- fix a situation to delete keys only when the slice has items.
https://issues.redhat.com/browse/HMS-4274
https://issues.redhat.com/browse/HMS-3525
=> fix(HMS-4274): rbac calls for system endpoints

configs/bonfire.example.yaml, configs/config.example.yaml, deployments/clowder.yaml, scripts/mk/private.example.mk
This change enable RBAC by default, this means the below:
- rbac is enabled by default when we run locally the service by `make run`. See: secrets/private.mk to avoid it is override the value.
- rbac is enabled by default when we deploy in dev cluster by `make ephemeral-deploy` or `make ephemeral-build-deploy`.
- rbac is enabled by default when we deploy in stage, unless the parameter APP_ENABLE_RBAC is override on deployment time.
=> feat(HMS-3528): enable rbac by default

internal/infrastructure/middleware/enforce_identity.go, internal/infrastructure/middleware/enforce_identity_test.go, internal/infrastructure/router/public.go, internal/test/builder/api/builder_user_xrhid.go, internal/usecase/interactor/domain_interactor.go
This change provide a new enforcement predicate for the
service accounts so it is checked the type and some data
are provided. It adds the new enforcement to the
middleware at the service router configuration. Finally
it add unit tests to cover the new enforcement predicate.
This PR implements: https://issues.redhat.com/browse/HMS-4280
That make easier the integration of smoke and integration tests for RBAC.
=> feat(HMS-3968): add service account to enforcement

internal/test/builder/api/builder_service_account_xrhid.go, internal/test/smoke/domain_delete_test.go, internal/test/smoke/domain_list_test.go, internal/test/smoke/domain_patch_user_test.go, internal/test/smoke/domain_read_test.go, internal/test/smoke/domain_update_system_test.go, internal/test/smoke/rbac_permission_test.go, internal/test/smoke/register_test.go, internal/test/smoke/suite_base_one_domain_test.go, internal/test/smoke/suite_base_test.go, internal/test/smoke/system_endpoints_test.go, internal/test/smoke/token_create_test.go
This PR add `As` semantics so it can be used for
set the RBACProfile or XRHIDProfile; we can provide
several in the list of arguments, and they are applied
from left to right; the last value is the one that take
effect. More details below:
About XRHID:
- As(XRHIDServiceAccount): it indicates that following
API operations will use a service account XRHID.
- As(XRHIDUser): it indicates that following API
operations will use a user XRHID.
- As(XRHIDSystem): it indicates that following API
operations will use a System XRHID.
- As(XRHIDNone): it indicates that following API operations
will not add any XRHID header. It forces to delete the
header when the request is made.
- As(XRHIDNothing): it indicates that following API
operations will not add / delete any XRHID header.
About RBAC:
- …
=> refactor(HMS-3968): add `As` semantics

internal/test/smoke/domain_delete_test.go, internal/test/smoke/domain_list_test.go, internal/test/smoke/domain_patch_user_test.go, internal/test/smoke/domain_read_test.go, internal/test/smoke/rbac_permission_test.go, internal/test/smoke/register_test.go, internal/test/smoke/suite_base_one_domain_test.go, internal/test/smoke/token_create_test.go
This change add service accounts to the rbac smoke
tests, and complete the existing smoke tests to
provide coverage for the service accounts where
required.
Depends on: https://github.com/podengo-project/idmsvc-backend/pull/232
=> test(HMS-3968): cover service accounts in smoke

README.md, docs/dev/TESTING.md
- Update example at dev documentation for `TESTING.md`, specifically the example using BodyFunc.
- Update examples to show how to use a service-accounts with scripts.
Depends on: https://github.com/podengo-project/idmsvc-backend/pull/236
=> doc(HMS-3968): update documentation

test/scripts/common.inc, test/scripts/ephe-domains-delete.sh, test/scripts/ephe-domains-list.sh, test/scripts/ephe-domains-patch.sh, test/scripts/ephe-domains-read.sh, test/scripts/ephe-domains-token.sh, test/scripts/local-domains-delete.sh, test/scripts/local-domains-list.sh, test/scripts/local-domains-patch.sh, test/scripts/local-domains-read.sh, test/scripts/local-domains-register.sh, test/scripts/local-domains-token.sh, test/scripts/local-domains-update.sh, test/scripts/local-hostconf.sh, test/scripts/local-signing-keys.sh
This change add service account support to the helper scripts
at `./scripts/test/*.sh` files.
We can specify `XRHID_AS={user,system,service-account}`, by
default it is used `user` account.
Depends on: https://github.com/podengo-project/idmsvc-backend/pull/233
=> chore(HMS-3968): update test scripts

internal/usecase/interactor/domain_interactor.go
The operations UpdateAgent and UpdateUser where referencing a wrong OrgID value from the XRHID structure. It has to reference Identity.OrgID which is set by the context when the XRHID enforcement is accepted, if fallback behavior is detected.
See: https://github.com/RedHatInsights/platform-go-middlewares/blob/master/identity/identity.go#L268
=> fix(HMS-4366): fix: using wrong OrgID

internal/infrastructure/middleware/enforce_identity.go, internal/infrastructure/middleware/enforce_identity_test.go, internal/test/builder/api/builder_system_xrhid.go
This change are a set of small changes observed during the
review at https://github.com/podengo-project/idmsvc-backend/pull/236
- Add multi-error for OR logical enforcement.
- Add check for Identity.AuthType==`cert-auth` enforcement for System endpoints.
- A unit test for the router started to fails. The fix is added here, but this was not observed on the pipeline.
=> fix(HMS-3968): multi-error enforce and minor fixes

internal/test/smoke/register_test.go, internal/usecase/interactor/domain_interactor.go, internal/usecase/interactor/domain_interactor_test.go
If a system makes the registration call (domains POST) with defined:
- title
- description
- auto_enrollment_enabled
Then the values are respected (unchanged).
If values are not defined or if title is empty then defaults are set.
=> feat(HMS-3596): respect defined values in registration

internal/handler/impl/domain_handler.go, internal/handler/impl/host_handler.go, internal/interface/interactor/domain_interactor.go, internal/test/mock/interface/interactor/domain_interactor.go, internal/usecase/interactor/domain_interactor.go, internal/usecase/interactor/domain_interactor_test.go
This is a fix/refactoring where the `domain_handler` is changed to use correct request type instead of `public.Domain` for PATCH and PUT. 
The `domains_interactor` is modified to reflect the changes.
This was made when working on HMS-2991 but it turned out that these changes are not needed for the ticket.
=> fix: request type of domains update PUT and PATCH

internal/infrastructure/middleware/metrics.go, internal/infrastructure/middleware/metrics_test.go, internal/infrastructure/router/public_test.go
This change include:
- Relax public router test so the goal of checking the routes is achieved, but we don't enter on to deep framework details.
- Fix a go vet violation at the metrics middleware where one of the implicit call is not deferred.
- Simplify Skipper invocation for the metrics middleware and add unit test for it.
=> fix(HMS-4373): small changes

internal/test/smoke/register_test.go
The test was intermittently failing with:
```
panic.go:261: test panicked: runtime error: invalid memory address or nil pointer dereference
goroutine 85 [running]:
runtime/debug.Stack()
/usr/local/go/src/runtime/debug/stack.go:24 +0x5e
github.com/stretchr/testify/suite.failOnPanic(0xc000583d40, {0x1bbac60, 0x2f99620})
/go/pkg/mod/github.com/stretchr/testify@v1.9.0/suite/suite.go:89 +0x37
github.com/stretchr/testify/suite.Run.func1.1()
/go/pkg/mod/github.com/stretchr/testify@v1.9.0/suite/suite.go:188 +0x25d
panic({0x1bbac60?, 0x2f99620?})
/usr/local/go/src/runtime/panic.go:914 +0x21f
github.com/podengo-project/idmsvc-backend/internal/test/smoke.(*SuiteRegisterDomain).TestRegisterDomain.func1(0xc000c22000?, 0xc000a96910)
/__w/idmsvc-backend/idmsvc-backend/internal/test/smoke/register_test.go …
```
=> test: fix nil pointer dereference in smoke/register_test.go

internal/handler/impl/domain_handler.go, internal/test/smoke/domain_update_system_test.go, internal/test/smoke/suite_base_test.go
Return 400 bad request when realm name is about to be changed as it is not possible to change a realm of an IPA server.
Note: the ticket discusses implementation in interactor and using `readOnly` property in API spec.  But this this is no-go as the check needs to be performed after loading the entry from DB (thus after interactor and all middlewares). 
As for review of other fields, the fields are mostly limited by the data structure of requests. To me, only the the RealmName seems as the field to check. PATH method (`UpdateDomainUserRequest` struct` is already quite limited and all fields are changeable).
=> fix(HMS-2991): fail on changing of realm in domains PUT

requirements-dev.txt
This change bump the dependencies to the latest versions but 'pre-commit' which has a bigger version change.
=> bump(rhin-1706): python requirements

build/package/Dockerfile
This change bump the base container image to the
current most recent version.
=> bump(rhin-1706): base container image

deployments/testing-integration.yaml
tests/test_domain_basic.py::test_domain_register[ViaWebUI] is failing with ERROR Exception looking up a domain within
context: <iqe.base.application.implementations.web_ui.ViaWebUI
Element is present but the click event is not working.
=> HMS-4436 fix: IQE test failing in Stage-Testing SaaS pipeline

deployments/testing-integration.yaml
Description: Docker images are not Supported and when Pipeline is trigger auto-promoter reported
Error: Image is not in imagePatterns: docker.io/selenium/standalone-chrome:4.18.1-20240224
=> Update IQE_SEL_IMAGE value to use quay.io images

deployments/testing-integration.yaml
The pipeline is paused at INFO: sending shutdown request to selenium... 
The issue was with tests, not images, so reverting to the old image.
=> Revert back to old image as the latest image is not stable

internal/infrastructure/context/gorm.go, internal/infrastructure/context/gorm_test.go, internal/infrastructure/context/slog.go, internal/infrastructure/context/slog_test.go
This change add primitives to add
`log` and `db` connector reference to the
`context.Context` for the request context,
and to recover from the `context.Context`.
The `db` connection belong to the request
scope too, so to keep consistency it is
added too.
Depends on: https://github.com/podengo-project/idmsvc-backend/pull/262
https://issues.redhat.com/browse/HMS-4276
=> feat(HMS-4276): add context primitives

internal/infrastructure/context/gorm.go, internal/infrastructure/context/gorm_test.go, internal/infrastructure/context/slog.go, internal/infrastructure/context/slog_test.go, internal/infrastructure/logger/middleware.go, internal/infrastructure/middleware/logger.go, internal/infrastructure/router/router.go, internal/infrastructure/service/impl/mock/rbac/impl/rbac.go
Add middleware which provide contextual log which print-out the `request-id` for all the messages:
- Add new middleware.
- Initialize middleware for the http router.
- Initialize middleware for the mock rbac service.
- Update current middleware to use the log instance from the request context.
Depends on: https://github.com/podengo-project/idmsvc-backend/pull/267
https://issues.redhat.com/browse/HMS-4276
=> feat(HMS-4276): add contextual log middleware

docs/dev/00-frameworks-and-libraries.md, docs/dev/09-logs.md, internal/handler/impl/domain_handler.go, internal/handler/impl/domain_handler_private.go, internal/handler/impl/host_handler.go, internal/handler/impl/keys_handler.go, internal/infrastructure/datastore/hostconf_jwk_db.go, internal/interface/repository/domain_repository.go, internal/interface/repository/host_repository.go, internal/interface/repository/hostconf_jwk_repository.go, internal/test/mock/interface/repository/domain_repository.go, internal/test/mock/interface/repository/host_repository.go, internal/test/mock/interface/repository/hostconf_jwk_repository.go, internal/usecase/repository/base_test.go, internal/usecase/repository/domain_repository.go, internal/usecase/repository/domain_repository_test.go, internal/usecase/repository/host_repository.go, internal/usecase/repository/host_repository_test.go, internal/usecase/repository/hostconf_jwk_repository.go, internal/usecase/repository/hostconf_jwk_repository_test.go
Provide contextual information to the log messages to
enhance the traceability.
TODO
----
https://issues.redhat.com/browse/HMS-4276
Depends on: https://github.com/podengo-project/idmsvc-backend/pull/276
=> feat(HMS-4276): use contextual logs

scripts/mk/private.example.mk
It was detected a wrong url into the
scripts/mk/private.example.mk file which
is used to get started the configuration
for the development environment.
This change update the url to renew the
token when we could need so it is easy
to make the operation for the developer.
=> fix: url to renew token

internal/infrastructure/middleware/enforce_identity.go, internal/infrastructure/middleware/enforce_identity_test.go, internal/infrastructure/middleware/logger.go, internal/infrastructure/middleware/rbac.go, internal/infrastructure/middleware/rbac_test.go, internal/usecase/client/inventory/host_inventory_test.go
If a middleware is configured after the contextual log, then it should use it, so the traceability
information is printed out with the messages.
This change add the above for enforcement and rbac middleware.
https://issues.redhat.com/browse/HMS-4522
=> fix(HMS-4522): use contextual log in middlewares

deployments/clowder.yaml
It was agreed as the least-verbose level accross all envs.
=> chore(HMS-4521): clowder - default logging level set to info

internal/infrastructure/router/public.go, internal/test/smoke/domain_list_test.go, internal/test/smoke/domain_patch_user_test.go, internal/test/smoke/domain_read_test.go, internal/test/smoke/domain_update_system_test.go, internal/test/smoke/register_test.go, internal/test/smoke/token_create_test.go
This change remove the RequestID middleware as
it would be duplicated then in the response to
then end user.
Credits on @pvoborni
=> fix(HMS-4544): remove RequestID middleware

deployments/backend-compose.yaml
backend-compose.yaml was not starting correcly from the following reasons:
- mock-rbac service didn't have valid configuration
- backend-service was using no longer support APP_SECRET=random
- it was not configured for mock-rbac but rbac is enabled by default
Needed for fixing CI job in ipa-hcc.
Q: I'm not sure what is the proper approach for the `APP_SECRET` when `random` is no longer supported.
=> chore: fix backend-compose

internal/infrastructure/middleware/enforce_identity_test.go
On fast system, the first and second time could have been the same. And thus the test failed.
Changing the condition to allow the same time.
=> test: fix race condition in enforce_identity_test.go

internal/usecase/client/pendo/pendo_client.go
The timeout was not using correct duration unit as default is Nanosecond.
So when used with defaults, the request almost immediately timed out.
=> fix: timeout duration of Pendo client

internal/infrastructure/middleware/metrics.go, internal/infrastructure/middleware/metrics_test.go, internal/infrastructure/router/public.go, internal/metrics/metrics.go
Removing the current metric (due to bad name) and also to not aggregate by status here.
It adds metrics:
- idmsvc_http_request_duration_seconds_bucket
- idmsvc_http_request_duration_seconds_sum
- idmsvc_http_request_duration_seconds_count
- idmsvc_http_requests_total
=> feat(HMS-1298): http request duration and total metrics

.gitlab-ci.yml, sonar-project.properties
Add SonarQube SAST job to git GitLab CI (needs to be GitLab because it reports to the
Red Hat internal SonarQube instance).
The GitLab `test` CI job has gone stale and doesn't work (due to no database service, and
other gaps).  Because we use GitHub for the main CI, I just disabled the tests in GitLab
rather than wrestling with them.
Because GitLab is mirroring from idmsvc, CI jobs do not run automatically.  I have set up
and **hourly** GitLab scheduled pipeline to run on the `main` branch.  After this changed
has been merged and everything is verified to be working, I will wind that back to daily
or weekly.
=> Add SonarQube job to GitLab CI

internal/config/config.go, internal/usecase/client/pendo/pendo_client.go, internal/usecase/client/pendo/pendo_client_test.go
Track Events and Metadata have slightly different endpoint URLs and also they use different API keys.
This change introduces the new config value for the track event key and changes the URLs.
Also now the base URL is expected to be e.g.: `https://app.pendo.io`.
Related to HMS-4503
=> fix: use different Pendo API keys base on endpoint

deployments/clowder.yaml
The change add the necessary environment variables to the deployment
so the client component can instantiate correctly.
Depends on: https://github.com/podengo-project/idmsvc-backend/pull/311
https://issues.redhat.com/browse/HMS-4531
=> feat(HMS-4531): inject pendo env vars

cmd/pendo-client/main.go, internal/config/config.go, internal/usecase/client/pendo/pendo_client.go, internal/usecase/client/pendo/pendo_client_test.go
A CLI wrapper for pendo client for testing the implementation. Starting with Track Events.
=> feat: Pendo test CLI client

.vscode/settings.json
The workspace settings has this set. It triggers the tests on each save which is sometimes undesired. E.g. when working on perf tests and launching the tests separately.
Removal of this options makes it still configurable on a user level - when the user prefers it enabled.
=> chore: remove vscode settings "Go: Cover on Save"

deployments/clowder.yaml, internal/config/config.go, internal/infrastructure/datastore/db.go
Introducing DATABASE_MAX_OPEN_CONN config env var to set $subj.
DB connection limit prevents reaching the same limit in database when processing a lot of concurrent requests.
30 was chosen as it is still less than 1/4th of db.t4g.small which could be the initial DB instance. Also it is less than 100 which is the default limit of Postgres container.
Note: I'm thinking it would be nice to print the config of the service on startup - with omitted or obfuscated secrets . To make it easier to validate the combination of clowder/env vars/defaults work in various envs.
=> fix(HMS-4690): configurable maximum of open DB connections

internal/usecase/client/pendo/pendo_client.go
In one call the body was not closed and in another it was not closed when HTTP status was other than OK.
Now, in both usages, it is "deferred" closed right after checking that response did not error-out (and thus `.Body` should be present).
Note: `// nolint:errcheck` is used as linter complains but the code used is the one mentioned in official docs of `net/http` package.
=> fix(HMS-1806): closing of http response body in Pendo client

internal/handler/impl/domain_handler.go, internal/handler/impl/domain_handler_private.go, internal/test/smoke/domain_delete_test.go, internal/test/smoke/domain_list_test.go, internal/test/smoke/domain_update_system_test.go, internal/test/smoke/register_test.go, internal/test/smoke/suite_base_one_domain_test.go, internal/test/smoke/suite_base_test.go
So that a server cannot DOS itself.
The patch is also fixing test flakiness when HCCUpdate == false by setting the HCCUpdate to true for register domain flows.
The check is the same as for ensureSubscriptionManagerIDAuthorizedToUpdate but the error is different (BadRequest vs Unauthorized).
=> fix(HMS-3393): reject domain update if server RHSM ID not in server list

internal/infrastructure/middleware/enforce_identity.go, internal/infrastructure/middleware/enforce_identity_test.go, internal/infrastructure/middleware/rbac_test.go, internal/infrastructure/router/public.go, internal/test/smoke/system_endpoints_test.go
If the HTML resource path is unrecognised, the EnforceIdentity middlewares all get skipped.  This causes the XRHID field in the context to be uninitialised.  As a consequence, the RBAC middleware panics because it expects the field to be set.
To avoid this issue, we create a new middleware which always sets the XHRID into the request context.  This middleware runs after the FakeIdentity middleware (if used), and before the EnforceIdentity and RBAC middlewares.
The EnforceIdentity middleware is simplified as a result; it no longer needs to parse the XRHID and can read it from the context.
=> fix: avoid panic due to unset XRHID on invalid path

cmd/service/main.go, internal/config/config.go, internal/config/config_test.go
Log also secrets but obfuscate them so that it is visible if they are set or not but not their value.
Setting as draft to get initial feedback. Qs:
- is it worth the time to implement tests for this. IMHO the only useful test would be to check that secrets are obfuscated. But to test it, it would need something like: https://pkg.go.dev/github.com/thejerf/slogassert#Handler.Assert 
- is the place where it is logged good? I.e before or after logger initialization? 
Example output:
> time=2024-10-03T18:02:34.477+02:00 level=INFO msg=idmscv-backend Version=(devel) Commit=5e87078ba927d1d626e84a7f873527abb357b4bf CommitTime=2024-10-03T06:00:45Z Dirty=true
> time=2024-10-03T18:02:34.478+02:00 level=INFO msg=idmsvc-backend Logging.Console=true Logging.Type=null Logging.Level=debug …
=> fix(HMS-4769): log configuration on startup

configs/bonfire.example.yaml, deployments/clowder.yaml, internal/infrastructure/service/impl/mock/rbac/impl/rbac_test.go
For clowder enabled environments where the endpoints are provided via e.g. ACG_CONFIG=/cdapp/cdappconfig.json., the value in CLIENTS_RBAC_BASE_URL is ignored.
Thus make it optional so that it doesn't have to be set in those envs.
=> fix(HMS-4760): make CLIENTS_RBAC_BASE_URL optional in clowder.yaml

.vscode/launch.json, internal/infrastructure/datastore/migration.go, scripts/mk/db.mk
db-tool had an issue that the `steps` arg was not used in practice and thus variant with `0` was always run.
There is an issue present in run  `db-tool migrate down 0` which ends with `panic: database locked`. But in practice the issue is:
```
migration failed: cannot drop table domains because other objects depend
on it, constraint fk_ipas_id__domains_id on table ipas depends on table domains
in line 0
```
I.e. one of the older `down` updates is not correct.
This patch is fixing handling of the `steps` arg to be used and it adds log statement to not hide error like the above.
In addition it adds new make file target to test it more easily and modifies vscode launch to use down by one step instead of all (the same in makefile target).
=> fix(HMS-4848): db-tool migrate down 1

scripts/db/migrations/20230125102205_create_table_domains.down.sql
This migration failed as the dropping of tables was done in wrong order (same as creation). The order must be reversed to the one in creation.
This is fixing it. And thus fixes `db-tool migrate down 0`.
Partly related to HMS-4848
Note: But I wonder if we actually want this to work as it prunes the database.
=> fix: db migration 20230125102205_create_table_domains.down

internal/handler/impl/application.go, internal/handler/impl/domain_handler.go, internal/handler/impl/domain_handler_private.go, internal/handler/impl/host_handler.go, internal/handler/impl/keys_handler.go
This change add logs for every handler of the application.
The change should be aligned to the [guidelines](https://github.com/podengo-project/idmsvc-backend/blob/main/docs/dev/09-logs.md#guidelines).
- Refactor some code to use logger form the context.
- Refactor some not found database conditions to return them.
https://issues.redhat.com/browse/HMS-4804
=> feat(HMS-4804): add logs to handlers

scripts/db/migrations/20241014130703_domains_org_index.up.sql
init container failed on creating the index saying that it already exists. It's not clear how we got to the situation. This changes tries to make this update file idepotent so that it won't fail in this situation.
=> fix: db migration to create index in indepotent way

internal/test/sql/helper.go, internal/test/sql/ipas_sql.go, internal/usecase/repository/domain_repository_test.go, internal/usecase/repository/host_repository_test.go
This change refactor helperTestFindByIDIpa function
into a simpler way, starting to create the package
internal/test/sql/ipas which will hold the code for
the SQL mock helpers, and making them more simple.
The public functions will match with the real
method/function. That helper will be currently
orquestating the preparation of the sql mock
statement. The first 3 arguments would be
(stage, mock, expectedErr, ...) where stage
is the step in the control flow, mock is the
sqlmock instance where prepare the expectations,
and expectedErr is nil for success or an error
reference for error expectations.
Additional functions named PrepSql... will
mock the specific SQL statement, decomposing
complex executions in smaller units. This functions
will haveas 3 first arguments: mock, withError and …
=> refactor(HMS-3803): helperTestFindByIDIpa to FindIpaByID

internal/domain/model/domain.go
Remove a missed Debug() invocation during the development.
=> chore: clean-up Debug() invocation

internal/infrastructure/datastore/db.go
Log the database version on service startup.  Example output:
```
2024/10/22 13:39:11 INFO SSL_CERT_DIR not updated
time=2024-10-22T13:39:11.525+10:00 level=INFO msg=idmscv-backend Version=(devel) Commit=b400ae2dbc80a70892a9525ceebea21512ec6391 CommitTime=2024-10-18T14:29:52Z Dirty=true
time=2024-10-22T13:39:11.527+10:00 level=INFO msg=idmsvc-backend Logging.Console=true Logging.Type=null Logging.Level=info Logging.Location=false
time=2024-10-22T13:39:11.527+10:00 level=NOTICE msg="Logging successfully initialized"
time=2024-10-22T13:39:11.527+10:00 level=INFO msg=Configuration Web.Port=8000 Database.Host=localhost Database.Port=5432 Database.User=idmsvc-user Database.Password=*** Database.Name=idmsvc-db Database.CACertPath="" Database.MaxOpenConns=30 Logging.Level=info …
```
=> log database version on service startup

internal/test/sql/domains_sql.go, internal/usecase/repository/domain_repository_test.go
This change refactor helperTestFindByID to the
internal/test/sql package following the guidelines
from the previous change.
Depends on: https://github.com/podengo-project/idmsvc-backend/pull/357
=> refactor(HMS-3803): helperTestFindByID to FindByID

internal/test/sql/domains_sql.go, internal/usecase/repository/domain_repository_test.go
Refactor the code from helperTestDeleteById method
to the test shared function DeleteByID into
the internal/test/sql package.
Depends on: https://github.com/podengo-project/idmsvc-backend/pull/358
=> refactor(HMS-3803): helperTestDeleteById to DeleteByID

internal/test/sql/domains_sql.go, internal/usecase/repository/domain_repository_test.go
This change refactor helperTestUpdateUser to UpdateUser
at the internal/test/sql package.
Depends on: https://github.com/podengo-project/idmsvc-backend/pull/359
=> refactor(HMS-3803): helperTestUpdateUser to UpdateUser

internal/test/sql/ipas_sql.go, internal/usecase/repository/domain_repository_test.go
Refactor the method helperTestCreateIpaDomain into
CreateIpaDomain at internal/test/sql package and divide
the function by separating the different SQL statements,
creating smaller functions.
Depends on: https://github.com/podengo-project/idmsvc-backend/pull/361
=> refactor(HMS-3803): helperTestCreateIpaDomain to CreateIpaDomain

internal/test/sql/domains_sql.go, internal/usecase/repository/domain_repository_test.go
Refactor TestUpdateUser making that more lineal and easier
to debug and trace the errors in the future.
This modify the signature for test_sql.UpdateUset to pass
as argument the domainID for the operation.
Depends on: https://github.com/podengo-project/idmsvc-backend/pull/364
=> refactor(HMS-3803): TestUpdateUser

internal/test/sql/domains_sql.go, internal/usecase/repository/domain_repository_test.go
Rename TestUpdateErrors to TestUpdateAgent and add
checks for the sqlmocks. This prepare for additional
changes.
Depends on: https://github.com/podengo-project/idmsvc-backend/pull/368
=> fix(HMS-3803): TestUpdateAgent add sqlmock checks

internal/test/smoke/domain_patch_user_test.go, internal/test/smoke/suite_base_test.go, internal/usecase/repository/domain_repository.go, internal/usecase/repository/domain_repository_test.go
Add additional guards for:
- UpdateAgent
- UpdateUser
- updateIpaDomain
And update the unit tests according to them.
Depends on: https://github.com/podengo-project/idmsvc-backend/pull/369
=> fix(HMS-3803): add additional guards

internal/usecase/repository/domain_repository.go, internal/usecase/repository/domain_repository_test.go
Update some differences observed with the final code
to fix:
- Update error messages making them more consistent
on the unit tests.
- Clean-up an initialization.
- Some renames to be more clear about the data that
is used at updateIpaDomain method.
Depends on: https://github.com/podengo-project/idmsvc-backend/pull/371
=> refactor(HMS-3803): align a bit more before the fix

internal/test/sql/domains_sql.go, internal/test/sql/ipas_sql.go, internal/test/variables.go, internal/usecase/repository/domain_repository.go, internal/usecase/repository/domain_repository_test.go
this change fix the flaky tests on the unit tests,
and align the SQL expectations closer to the reality.
Randomly sometimes the ID was included into the SQL
statement, when it was expected to be 0.
The changes on this make the code more predictible,
and the tests are more deterministic.
Depends on: https://github.com/podengo-project/idmsvc-backend/pull/372
=> fix(HMS-3803): flaky tests on unit tests

cmd/db-tool/main.go, cmd/mock-rbac/main.go, cmd/pendo-client/main.go, cmd/service/main.go, internal/infrastructure/logger/init.go, internal/test/smoke/suite_base_test.go
This change refactor the log initialization to use the same code for all the generated binaries. Provide consistency.
https://issues.redhat.com/browse/HMS-4864
=> refactor(HMS-4864): align all binaries for the logs

README.md, scripts/mk/ephemeral.mk
- Add delve package installation to debug golang
source code from vscode.
- Fix a typo in the command to use a different rbac profile.
- Fix up some rbac commands:
- The path for curl command should be to /api/rbac/v1/access?application=idmsvc
- Add an unauthorized command to check the readonly profile is
being used.
- Add comments to let the developer know what is the
expected result when launching the test scripts locally.
- Filter a no wished log trace.
=> doc: update README.md

scripts/mk/private.example.mk
This change update the `private.example.mk` template to add the `QUAY_EXPIRATION` variable and documentation about where it is leveraged and link to the official documentation about the label that it sets the value.
It sets empty the `QUAY_REPOSITORY` variable, which was setting the value for `QUAY_EXPIRATION`.
=> chore: add QUAY_EXPIRATION to the template

cmd/db-tool/main.go, cmd/mock-rbac/main.go, cmd/pendo-client/main.go, cmd/service/main.go, internal/infrastructure/logger/init.go, internal/test/smoke/suite_base_test.go
Tweaked and rebased variant of PR #410.  I was unable to force-push directly to @avisiedo's branch because of the commit signing requirement, so I made an alternative PR instead.
=> fix(HMS-4864): flush cloudwatch logs (PR #410 redux)

.dockerignore, .tekton/idmsvc-backend-pull-request.yaml, .tekton/idmsvc-backend-push.yaml, build/package/Dockerfile
Prepare the change for adding the unit test task, by migrating the tasks to -oci-ta which does not require PVC and the ephemeral information is trusted.
This change apply to the pullrequest tekton pipeline.
https://issues.redhat.com/browse/HMS-4556
---
TODO
=> refactor(HMS-4895): use -oci-tag wherever possible

.tekton/idmsvc-backend-push.yaml
Add the ociStorage required parameter
See: https://github.com/konflux-ci/build-definitions/tree/main/task/git-clone-oci-ta/0.1
https://issues.redhat.com/browse/HMS-4895
=> fix(HMS-4895): add required ociStorage param

.tekton/idmsvc-backend-push.yaml
- Refactor build-container to build-images to be aligned with the pull-request pipeline, and update the references.
- This is expected that will fix the message: `Cannot find Dockerfile build/package/Dockerfile`
=> fix(HMS-4895): push image tekton pipeline

.tekton/idmsvc-backend-push.yaml
The prefetch-dependencies task was not using
the -oci-ta reference; this change add that
so it is aligned with -oci-ta refactor.
=> fix(HMS-4895): invalid resource reference

.tekton/idmsvc-backend-push.yaml
This change update the push-dockerfile task to use the
bundle aligned with -oci-ta; missed change during updating
the build pipeline.
This should fix the message `Cannot find Dockerfile
build/package/Dockerfile`
https://issues.redhat.com/browse/HMS-4895
=> fix(HMS-4895): missed push-dockerfile task refactor

build/package/Dockerfile
mock-rbac and service container builds both use UBI 9 Minimal, but from two different repos.  This causes separate (and additional) bot PRs when the image(s) get updated.
Make both builds use the `ubi9/ubi-minimal` repository.  As a result, future updates should trigger a single PR which updates both references.
=> chore(deps): unify ubi9 image sources

internal/test/sql/domains_sql.go, internal/test/sql/ipas_sql.go
The change does not modify or impact anything, but make the definition aligned
according with the implementation.
=> chore: typo "deletet_at" > "deleted_at"
