- build/package/Dockerfile
- Use golang 1.19
- Use latest stable UBI 9.2 container
> refactor: Update build and compose container

- configs/config.example.yaml
- internal/config/config.go
- internal/infrastructure/event/consumer.go
- internal/infrastructure/logger/init.go
This adds some improvements for logging like wiring a config option to print source code locations.
> HMS-3196: Some logging improvements

- .github/workflows/main.yml
- deployments/backend-compose.yaml
- deployments/clowder.yaml
- deployments/docker-compose.yaml
Use Postgres 15 from quay.io/cloudservices/postgresql-rds and in Clowder configuration.
> HMS-3462 infra: Test and deploy with Postgres 15

- requirements-dev.txt
Upgrade crc-bondire to 5.5.0 version
https://github.com/RedHatInsights/bonfire/releases/tag/v5.5.0
> bump: crc-bonfire to 5.5.0 version

- internal/test/builder/api/builder_host_conf.go
- internal/test/builder/model/builder_domain.go
- internal/test/builder/model/builder_host_conf_options.go
- internal/test/builder/model/builder_ipa_cacert.go
- internal/test/builder/model/builder_ipa_location.go
- internal/usecase/interactor/domain_interactor_test.go
- internal/usecase/repository/base_test.go
- internal/usecase/repository/domain_repository.go
- internal/usecase/repository/domain_repository_test.go
- internal/usecase/repository/host_repository.go
- internal/usecase/repository/host_repository_test.go
This change add unit tests for:
- DeleteById
- wrapErrNotFound
- Register
- MatchDomain
- WIP
> test(HMS-3507): enhance unit tests

- requirements-dev.txt
Bump bonfire version on the dependencies.
> bump(bonfire): version 5.7.x

- internal/usecase/repository/domain_repository.go
- internal/usecase/repository/domain_repository_test.go
- internal/usecase/repository/host_repository.go
- internal/usecase/repository/hostconf_jwk_repository.go
Every error on the database components now print a log
message with the error string.
TODO
> feat(HMS-3776):  print log on database error

- README.md
- docs/dev/00-frameworks-and-libraries.md
- docs/dev/08-rbac.md
- docs/dev/TESTING.md
Update developer documentation adding a new rbac section to the development documentation.
> doc(HMS-3527): add rbac dev documentation

- docs/db-model.puml
This change re-generate the current database model. By: `make build-all`
> doc: update db model

- internal/usecase/repository/domain_repository.go
- internal/usecase/repository/host_repository.go
- internal/usecase/repository/hostconf_jwk_repository.go
Add to the comments of the public functions
what is expected to read from the ctx context.Context argument.
> doc(HMS-4276): add ctx information

- internal/infrastructure/middleware/enforce_identity.go
- internal/infrastructure/middleware/enforce_identity_test.go
This change aggregate the org_id and the identity
information to the contextual log, so the information
is printed out for any log message.
> feat(HMS-4520): aggregate identity information

- internal/api/header/const.go
- internal/infrastructure/middleware/logger.go
- internal/infrastructure/middleware/logger_test.go
This change add the source_ip aggregated field to the logs.
https://issues.redhat.com/browse/HMS-4545
> feat(HMS-4545): add source ip to logs

- scripts/curl.sh
- test/scripts/common.inc
- test/scripts/stage-domains-delete.sh
- test/scripts/stage-domains-list.sh
- test/scripts/stage-domains-patch.sh
- test/scripts/stage-domains-register.sh
- test/scripts/stage-domains-token.sh
- test/scripts/stage.inc
Add a set of scripts to make life easier when
dealing with stage environment.
> test: add stage scripts

- configs/config.ci.yaml
- configs/config.example.yaml
- internal/api/header/const.go
- internal/config/config.go
- internal/interface/client/pendo/pendo.go
- internal/interface/client/pendo/pendo_api.go
- internal/test/builder/clients/pendo/builder_setmetadatadetailsrequest.go
- internal/test/builder/clients/pendo/builder_setmetadatarequest.go
- internal/test/builder/clients/pendo/builder_setmetadataresponse.go
- internal/usecase/client/pendo/pendo_client.go
- internal/usecase/client/pendo/pendo_client_dump.go
- internal/usecase/client/pendo/pendo_client_test.go
This change implement a pendo client,
and add the necessary changes to
update the config template, and read
the pendo configuration.
This add only the used endpoint.
https://issues.redhat.com/browse/HMS-4532
> feat(HMS-4532): pendo client

- cmd/service/main.go
- internal/handler/impl/application.go
- internal/handler/impl/application_test.go
- internal/infrastructure/router/public_test.go
- internal/infrastructure/router/router_test.go
- internal/infrastructure/service/impl/application.go
- internal/test/smoke/suite_base_test.go
This change instantiate the client pendo
component and inject to make it available at
the application service scope.
More changes could be necessary depending on
where it will be used.
> feat(HMS-4532): integrate pendo client

- internal/config/config.go
- internal/config/config_test.go
- test/scripts/generate-cert.sh
Add support for encrypted in-cluster communication.
TODO:
https://issues.redhat.com/browse/HMS-4617
> feat(HMS-4617): tls in-cluster communication

- internal/infrastructure/middleware/enforce_identity.go
Use function at header package to decode XRHID.
> chore: clean-up decodeXRHID

- dashboards/grafana-dashboards-idmsvc-configmap.yaml
This change land the initial grafana dashboard generated for the
service observability.
https://issues.redhat.com/browse/HMS-4642
> feat(HMS-4642): add grafana dashboard

- internal/domain/model/domain.go
- scripts/db/migrations/20241014130703_domains_org_index.down.sql
- scripts/db/migrations/20241014130703_domains_org_index.up.sql
As this field is present in all searches.
> fix(HMS-4809): add org_id index to domains table

- internal/domain/model/ipa.go
- internal/test/builder/api/builder_domain_update_request.go
- internal/test/builder/model/builder_model.go
This change add small fixes and chore
before enter into fixing the flaky tests.
They where detected during the fixing
of HMS-3803.
> fix(3803): small fixes pre-hms-3803

- internal/test/builder/model/builder_domain.go
Small fix that add a missed method for the Domain builder.
> fix(HMS-3803): add WithDomainName to Domain builder

- .yamllint.yaml
Supporting: https://github.com/podengo-project/idmsvc-backend/pull/378
> Ignore tekton directory for yamllint

- internal/test/sql/domains_sql.go
- internal/usecase/repository/domain_repository_test.go
Move helperTestRegister to Register at internal/test/sql
package where the function is decomposed their sql
statements.
Depends on: https://github.com/podengo-project/idmsvc-backend/pull/360
> refactor(HMS-3803): helperTestRegister to Register

- internal/test/sql/ipas_sql.go
- internal/usecase/repository/domain_repository_test.go
Refactor helperTestUpdateIpaDomain to UpdateIpaDomain
into the internal/test/sql package, divide the SQL statements
in smaller functions and reuse existing functions to orquestate
the expectations.
Depends on: https://github.com/podengo-project/idmsvc-backend/pull/362
> refactor(HMS-3803): helperTestUpdateIpaDomain to UpdateIpaDomain

- internal/test/sql/domains_sql.go
- internal/usecase/repository/host_repository_test.go
This refactor move helperTestMatchDomain method to the
internal/test/sql package and divide the sql statements
in functions for better maintenance.
Depends on: https://github.com/podengo-project/idmsvc-backend/pull/363
> refactor(HMS-3803): helperTestMatchDomain to MatchDomain

- README.md
- cmd/db-tool/cmd/jwk-list.go
- cmd/db-tool/cmd/jwk-purge.go
- cmd/db-tool/cmd/jwk-refresh.go
- cmd/db-tool/cmd/jwk-revoke.go
- cmd/db-tool/cmd/migrate-up.go
- cmd/db-tool/main.go
- cmd/mock-rbac/main.go
- go.mod
- internal/infrastructure/datastore/hostconf_jwk_db.go
- internal/infrastructure/datastore/migration.go
- internal/test/smoke/system_endpoints_test.go
This change provide logs to db-tool which includes migrations and key rotation.
https://issues.redhat.com/browse/HMS-4864
> fix(HMS-4864): add logs to db-tool

- configs/bonfire.example.yaml
Update the bonfire template for:
- Select the last trusted image generated for the frontend.
- Add SERVICE_REPLICAS
- Add DATABASE_MAX_CONNS
- Add documentation to clarify the values that take affect on each moment for the above ones.
> refactor: update bonfire template

- dashboards/grafana-dashboards-idmsvc-configmap.yaml
This change add a variable to the dashboard which
represent the datasource and it will point out to
the prometheus instance.
https://issues.redhat.com/browse/HMS-4922
> fix(HMS-4922): fix grafana dashboard
